name: build-tesseract-static

on:
  workflow_dispatch:
    inputs:
      tess_version:
        description: "Tesseract tag (e.g. 5.3.4)"
        default: "5.3.4"
      languages:
        description: "Space-separated list of .traineddata to include"
        default: "eng deu"

jobs:
  build:
    runs-on: ubuntu-latest
    # Use newer Amazon Linux that has compatible GLIBC
    container: amazonlinux:2023
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install build dependencies
        run: |
          dnf install -y \
            gcc gcc-c++ make automake autoconf libtool \
            git wget tar gzip \
            leptonica-devel
      
      - name: Build Tesseract ${{ inputs.tess_version }}
        run: |
          set -e
          git clone --depth 1 --branch ${TESS_VERSION} https://github.com/tesseract-ocr/tesseract
          cd tesseract
          ./autogen.sh
          ./configure --prefix=/opt/tesseract --disable-shared \
                      CFLAGS="-O2 -static" CXXFLAGS="-O2 -static"
          make -j$(nproc)
          make install-strip
        env:
          TESS_VERSION: ${{ inputs.tess_version }}
      
      - name: Add language data
        if: inputs.languages != 'eng'
        run: |
          mkdir -p /opt/tesseract/share/tessdata
          for L in $LANGS ; do
            wget -q https://github.com/tesseract-ocr/tessdata_best/raw/main/$L.traineddata \
                 -O /opt/tesseract/share/tessdata/$L.traineddata
          done
        env:
          LANGS: ${{ inputs.languages }}
      
      - name: Create tarball
        run: |
          cd /opt
          tar -czf $GITHUB_WORKSPACE/tesseract-static.tar.gz tesseract
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tesseract-static
          path: ${{ github.workspace }}/tesseract-static.tar.gz