name: build-tesseract-static

on:
  workflow_dispatch:
    inputs:
      tess_version:
        description: "Tesseract tag (e.g. 5.3.4)"
        default: "5.3.4"
      languages:
        description: "Space-separated list of .traineddata to include"
        default: "eng deu"

jobs:
  build:
    runs-on: ubuntu-latest
    container: amazonlinux:2023
    
    steps:
      # First install basic tools needed by GitHub Actions
      - name: Install basic utilities
        run: |
          dnf install -y tar gzip git
      
      # Now checkout will work
      - uses: actions/checkout@v3
      
      - name: Install build dependencies
        run: |
          # First try to find the correct package name for OpenJPEG
          dnf search openjp || echo "No OpenJPEG packages found"
          
          # Install compilation tools and dependencies for image libraries
          # Removed libopenjp2-devel which doesn't exist
          dnf install -y \
            gcc gcc-c++ make automake autoconf libtool pkg-config \
            wget \
            zlib-devel libpng-devel libjpeg-devel libtiff-devel \
            giflib-devel libwebp-devel
      
      - name: Build Leptonica from source
        run: |
          set -e
          cd /tmp
          wget https://github.com/DanBloomberg/leptonica/releases/download/1.83.1/leptonica-1.83.1.tar.gz
          tar -xzf leptonica-1.83.1.tar.gz
          cd leptonica-1.83.1
          ./configure --prefix=/usr
          make -j$(nproc)
          make install
          # Update the dynamic linker cache
          ldconfig
      
      - name: Build Tesseract ${{ inputs.tess_version }}
        run: |
          set -e
          git clone --depth 1 --branch ${TESS_VERSION} https://github.com/tesseract-ocr/tesseract
          cd tesseract
          ./autogen.sh
          ./configure --prefix=/opt/tesseract --disable-shared \
                      CFLAGS="-O2 -static" CXXFLAGS="-O2 -static"
          make -j$(nproc)
          make install-strip
        env:
          TESS_VERSION: ${{ inputs.tess_version }}
      
      - name: Add language data
        if: inputs.languages != 'eng'
        run: |
          mkdir -p /opt/tesseract/share/tessdata
          for L in $LANGS ; do
            wget -q https://github.com/tesseract-ocr/tessdata_best/raw/main/$L.traineddata \
                 -O /opt/tesseract/share/tessdata/$L.traineddata
          done
        env:
          LANGS: ${{ inputs.languages }}
      
      - name: Create tarball
        run: |
          cd /opt
          tar -czf $GITHUB_WORKSPACE/tesseract-static.tar.gz tesseract
      
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: tesseract-static
          path: ${{ github.workspace }}/tesseract-static.tar.gz