name: download-tesseract-languages

on:
  workflow_dispatch:
    inputs:
      languages:
        description: "Space-separated list of languages to include (eng deu fra etc)"
        default: "eng deu"

jobs:
  download:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download pre-built tesseract
        run: |
          mkdir -p tesseract-static/share/tessdata
          # Download pre-built static binary
          curl -L -o tesseract.tar.gz https://github.com/bweigel/aws-lambda-tesseract-layer/releases/download/v5.0.1/tesseract5-amazonlinux2.tar.gz
          # Extract bin directory
          tar -xf tesseract.tar.gz -C tesseract-static --strip-components=1 bin
      
      - name: Download language files
        run: |
          # Download all requested language files
          mkdir -p tesseract-static/share/tessdata
          for LANG in ${{ inputs.languages }}; do
            echo "Downloading $LANG.traineddata"
            curl -L -o tesseract-static/share/tessdata/$LANG.traineddata \
              https://github.com/tesseract-ocr/tessdata_best/raw/main/$LANG.traineddata
          done
          
          # Create tarball
          tar -czf tesseract-static.tar.gz -C tesseract-static .
          
          # List contents for verification
          echo "Contents of archive:"
          tar -tvf tesseract-static.tar.gz
      
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: tesseract-static
          path: tesseract-static.tar.gz